### ISSUE TITLE
Is there any plan for ready packages? 

### ISSUE THREAD

**Issue by EpsilonKu** [rohit-px2/nvui#18]
Also what about instruction to build?

**Comment by rohit-px2** [comment]
Hi! There are builds for Linux and Windows (x64) under the "Actions" tab.
As for the build instructions, I have some building instructions under the "BUILDING.md" file, but those haven't been updated (also when I made that, I wasn't aware of how many packages you needed to install on Linux).

**Comment by rohit-px2** [comment]
I've updated BUILDING.md with some additional information as to how to build the project, let me know if there's anything else you need

**Comment by michaelb** [comment]
@rohit-px2 , there's a splendid github action that would probably be useful (upload-release-action).

Given the current level of your Actions, this should be within reach and add a lot of value

For example, here's my auto-release config, which publish a binary to Releases each time I push a new "vX.Y.Z" tag
```
on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always


jobs:
  release:
    name: Publish release
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: cargo build --release --verbose && mv ./target/release/sniprun .

    - name: upload to releases
      uses: svenstaro/upload-release-action@v2 
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: sniprun
        tag: ${{github.ref}}
        overwrite: false
        body: "Automated publish by Github Action"
```
